# Scaffolding generated by Casein v5.1.1.3

module Casein
  class EventsController < Casein::CaseinController

    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]


    def index
      @casein_page_title = 'Events'
  		@events = Event.order(sort_order(:date)).paginate :page => params[:page]
      set_locale
    end

    def show
      @casein_page_title = 'View event'
      @event = Event.find params[:id]
      set_locale
    end

    def new
      @casein_page_title = 'Add a new event'
    	@event = Event.new
      set_locale
    end

    def create
      @event = Event.new event_params

      if @event.save
        flash[:notice] = 'Event created'
        redirect_to casein_events_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new event'
        render :action => :new
      end
    end

    def update
      @casein_page_title = 'Update event'

      @event = Event.find params[:id]

      if @event.update_attributes event_params
        flash[:notice] = 'Event has been updated'
        redirect_to casein_events_path
      else
        flash.now[:warning] = 'There were problems when trying to update this event'
        render :action => :show
      end
      set_locale
    end

    def destroy
      @event = Event.find params[:id]

      @event.destroy
      flash[:notice] = 'Event has been deleted'
      redirect_to casein_events_path
    end

    private

      def event_params
        params.require(:event).permit(:title, :title_fr, :speaker, :building, :building_fr, :address, :zip, :city, :country, :country_fr, :image, :details, :details_fr, :website, :additionnal_website, :date_from, :date)
      end

  end
end
