# Scaffolding generated by Casein v5.1.1.3

module Casein
  class TestimonialsController < Casein::CaseinController

    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]


    def index
      @casein_page_title = 'Testimonials'
  		@testimonials = Testimonial.order(sort_order(:name)).paginate :page => params[:page]
      set_locale
    end

    def show
      @casein_page_title = 'View testimonial'
      @testimonial = Testimonial.find params[:id]
      set_locale
    end

    def new
      @casein_page_title = 'Add a new testimonial'
    	@testimonial = Testimonial.new
      set_locale
    end

    def create
      @testimonial = Testimonial.new testimonial_params

      if @testimonial.save
        flash[:notice] = 'Testimonial created'
        redirect_to casein_testimonials_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new testimonial'
        render :action => :new
      end
    end

    def update
      @casein_page_title = 'Update testimonial'

      @testimonial = Testimonial.find params[:id]

      if @testimonial.update_attributes testimonial_params
        flash[:notice] = 'Testimonial has been updated'
        redirect_to casein_testimonials_path
      else
        flash.now[:warning] = 'There were problems when trying to update this testimonial'
        render :action => :show
      end
      set_locale
    end

    def destroy
      @testimonial = Testimonial.find params[:id]

      @testimonial.destroy
      flash[:notice] = 'Testimonial has been deleted'
      redirect_to casein_testimonials_path
    end

    private

      def testimonial_params
        params.require(:testimonial).permit(:name, :image, :image_pos, :text, :text_fr)
      end

  end
end
