default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000

production: &production
  <<: *default
  database: cindysauvain
  username: <%= ENV['PG_SQL_PROD_USER'] %>
  password: <%= ENV['PG_SQL_PROD_PASS'] %>

production_local:
  <<: *production

development:
  <<: *default
  database: cindy_dev
  username: <%= ENV['PG_SQL_DEV_USER'] %>
  password: <%= ENV['PG_SQL_DEV_PASS'] %>
