default: &default
  endpoint: 'https://acme-v01.api.letsencrypt.org/'
  email: 'admin@cindysauvain.com'
  domain: 'cindysauvain.com www.cindysauvain.com'

  # in Rails.root, path to private key
  private_key: 'ssl/key/cindysauvain.com.pem'

  # in Rails.root, path where certificates
  # will be stored (on Heroku this variable is ignored)
  output_cert_dir: 'ssl/certificates'

  # in Rails.root, path where challenge token
  # will be stored in case when DB will not be used
  challenge_dir_name: 'ssl/challenge'

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default